stages:
  train:
    cmd: python3 src/train.py
    deps:
    - data/raw/houses.csv
    - src/train.py
    outs:
    - models/house_predictor.joblib
    metrics:
    - metrics.json:
        cache: false
